

# ============================================
# APPLICATION
# ============================================
spring.application.name=employee-management-backend


# ============================================
# DATABASE
# ============================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/employee_management_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ============================================
# EMAIL / GMAIL SMTP
# ============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8


# ============================================
# GEMINI AI
# ============================================
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models
gemini.model=${GEMINI_MODEL:gemini-3.6-flash}


# ============================================
# SERVER
# ============================================
server.port=${PORT:8080}


